### ISSUE TITLE
1.19.2 Crash with Harvest Scythes (Mythic Metals new update)

### ISSUE THREAD

**Issue by gamerpotion** [Noaaan/MythicMetals#119]
Hey :)

just to update, there seems to be some conflict with Harvest Scythes after upgrading Mythic Metals to mythicmetals-0.16.0+1.19.2.jar

```---- Minecraft Crash Report ----
// You're mean.

Time: 2022-10-03 01:36:27
Description: Initializing game

java.lang.NoClassDefFoundError: nourl/mythicmetals/tools/ToolMaterials
	at wraith.harvest_scythes.support.MythicMetalsSupport.lambda$loadItems$0(MythicMetalsSupport.java:13)
	at wraith.harvest_scythes.registry.ItemRegistry.registerItem(ItemRegistry.java:62)
	at wraith.harvest_scythes.support.MythicMetalsSupport.loadItems(MythicMetalsSupport.java:13)
	at wraith.harvest_scythes.HarvestScythes.load(HarvestScythes.java:42)
	at net.minecraft.class_310.handler$cdk000$inject(class_310.java:14948)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: nourl.mythicmetals.tools.ToolMaterials
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at wraith.harvest_scythes.support.MythicMetalsSupport.lambda$loadItems$0(MythicMetalsSupport.java:13)
	at wraith.harvest_scythes.registry.ItemRegistry.registerItem(ItemRegistry.java:62)
	at wraith.harvest_scythes.support.MythicMetalsSupport.loadItems(MythicMetalsSupport.java:13)
	at wraith.harvest_scythes.HarvestScythes.load(HarvestScythes.java:42)
	at net.minecraft.class_310.handler$cdk000$inject(class_310.java:14948)
	at net.minecraft.class_310.<init>(class_310.java:459)```

**Comment by Sunconure11** [comment]
Having the same error. @LordDeatHunter 

https://pastebin.com/dyc7iq22

**Comment by LordDeatHunter** [comment]
I merged the PR.
Unfortunately, I am unable to make a release until the 10th of October at the earliest.
