### ISSUE TITLE
Crash with entity in 1.19.2 FABRIC 0.14.11

### ISSUE THREAD

**Issue by pokesmells** [Noaaan/MythicMetals#137]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-12-08 16:20:44
Description: Ticking entity

java.lang.RuntimeException: The stack 0 air was in a state of being empty and not being empty, report this!
	at net.minecraft.class_1309.mythicmetals$addArmorEffects(class_1309.java:61769)
	at net.minecraft.class_1309.handler$ikk000$mythicmetals$tick(class_1309.java:61707)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:760)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:9571)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1309.mythicmetals$addArmorEffects(class_1309.java:61769)
	at net.minecraft.class_1309.handler$ikk000$mythicmetals$tick(class_1309.java:61707)
	at net.minecraft.class_1309.method_5773(class_1309.java)
	at net.minecraft.class_1308.method_5773(class_1308.java:353)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:760)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:9571)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
The following mixins were found in the stacktrace: No Mixins Found
Mixins in Stacktrace: None found

-- Entity being ticked --
Details:
	Entity Type: mca:female_villager (fabric.net.mca.entity.VillagerEntityMCA)
	Entity ID: 30774
	Entity Name: Krasimira
	Entity's Exact location: -1444.44, 76.56, 278.84
	Entity's Block location: World: (-1445,76,278), Section: (at 11,12,6 in -91,4,17; chunk contains blocks -1456,-64,272 to -1441,319,287), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,-64,0 to -1025,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:9571)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

**Comment by pokesmells** [comment]
[crash-2022-12-08_16.20.44-client.txt](https://github.com/Noaaan/MythicMetals/files/10190237/crash-2022-12-08_16.20.44-client.txt)

mythicmetals-0.16.4+1.19.2.jar - Version being used.

**Comment by Noaaan** [comment]
This is a known issue and is documented in #94
I am changing the check I am using to not immediately crash if this happens, although due to the nature of this issue, it has the chance to crash anyway, since it is NOT supposed to happen.
