### ISSUE TITLE
Cannot invoke "net.minecraft.class_1309.method_5998(net.minecraft.class_1268)" because "attacker" is null

### ISSUE THREAD

**Issue by Mg138** [Noaaan/MythicMetals#142]
Using the latest version of MM.

```
[23:54:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Colliding entity with block
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$foe000$modifiedRunLoop(MinecraftServer.java:12885) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5998(net.minecraft.class_1268)" because "attacker" is null
        at net.minecraft.class_1309.handler$ghg000$mythicmetals$damageCarmotStaffOnXpDrop(class_1309.java:55763) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_23883(class_1309.java:1404) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_16080(class_1309.java:1396) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6078(class_1309.java:1348) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1204) ~[server-intermediary.jar:?]
        at net.darkhax.bookshelf.api.damagesource.FakePlayerDamageSource.causeDamage(FakePlayerDamageSource.java:56) ~[Bookshelf-Fabric-1.19.2-16.2.17.jar:?]
        at net.darkhax.darkutilities.features.flatblocks.FlatTileEffects.lambda$static$2(FlatTileEffects.java:31) ~[DarkUtilities-Fabric-1.19.2-13.1.7.jar:?]
        at net.darkhax.darkutilities.features.flatblocks.FlatTileEffects.lambda$livingEffect$6(FlatTileEffects.java:74) ~[DarkUtilities-Fabric-1.19.2-13.1.7.jar:?]
        at net.darkhax.darkutilities.features.flatblocks.BlockFlatTile.method_9548(BlockFlatTile.java:68) ~[DarkUtilities-Fabric-1.19.2-13.1.7.jar:?]
        at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$bom000$checkBlockCollisionBetter(class_1297.java:13632) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.redirect$bom000$onEntityCollision(class_1297.java:13600) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_26318(class_1309.java:2282) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6091(class_1309.java:2227) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2680) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_6007(class_1308.java:553) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5773(class_1308.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.class_1621.method_5773(class_1621.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18762(class_3218.java:712) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[server-intermediary.jar:?]
        at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.redirect$bhc000$catchExceptions(MinecraftServer.java:5782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
        ... 6 more

```

**Comment by Mg138** [comment]
Forgot to mention, this is a server crash.

**Comment by Noaaan** [comment]
Did... someone try to use a block or something to attack something with a Lapis-filled Carmot Staff?
This is based

**Comment by Mg138** [comment]
Not that we think someone did, we don't think we even have a fake player block in the pack?..

**Comment by Mg138** [comment]
Oh, we think we see it now.

We think your mixin applies to all and every time anything attacks anything, and the method fails when the attacker is null, which happens as long as there's a fake-player attacker, like Dark Utilities' plates.
