### ISSUE TITLE
MythicMetals Crashing Servers

### ISSUE THREAD

**Issue by PixelatedBruh** [Noaaan/MythicMetals#24]
I cannot get the mod to run at all on fabric server.

Tested 0.9.9-D, 0.9.9-C, and 0.9.8

nothing other than fabric api and mythicmetals

all cause the server to crash

[14:56:09] [main/INFO]: Loading for game Minecraft 1.16.5
[14:56:10] [main/INFO]: [FabricLoader] Loading 50 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.1, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.29.4+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.10+ca58154a7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, enchant_giver@1.0.2, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.8.3, fabric-resource-loader-v0@0.4.2+ca58154a7d, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, mythicmetals@0.9.9-snapshot-D
[14:56:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/minecraft/multicraft/servers/server131080/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:56:24] [main/INFO]: [Enchant Giver] has been initiated.
[14:56:26] [main/INFO]: [Mythic Metals] Mythic Metals is now initialized
[14:56:30] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:56:30] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[14:56:33] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:56:33] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:56:33] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:56:33] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:56:33] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:56:33] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Mythic Metals)
[14:56:39] [Worker-Main-10/INFO]: Loaded 7 recipes
[14:56:41] [Worker-Main-10/INFO]: Loaded 927 advancements
[14:56:46] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
[14:56:46] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
[14:56:46] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
[14:56:46] [main/INFO]: [STDERR]: 	... 1 more
[14:56:46] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[14:56:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:56:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:56:46] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:56:46] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
[14:56:46] [main/INFO]: [STDERR]: 	... 2 more
[14:56:46] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
[14:56:46] [main/INFO]: [STDERR]: 	... 7 more
[14:56:46] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[14:56:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:56:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:56:46] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:56:46] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[14:56:46] [main/INFO]: [STDERR]: 	... 9 more
[14:56:46] [main/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: net.minecraft.class_2378.method_10250(Lnet/minecraft/class_2960;)Z
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.biome.v1.BiomeSelectors.lambda$builtIn$1(BiomeSelectors.java:58)
[14:56:46] [main/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.modifyBiomes(BiomeModificationImpl.java:147)
[14:56:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_5382.handler$zca000$afterCreation(class_5382.java:554)
[14:56:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_5382.method_29753(class_5382.java:51)
[14:56:46] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.redirect$zbl000$ofRegistryOps(Main.java:1051)
[14:56:46] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:146)
[14:56:46] [main/INFO]: [STDERR]: 	... 14 more

**Comment by Noaaan** [comment]
Interesting crash. First of all what version of Fabric and Fabric API are you using?
Secondly, does it load properly in singleplayer?

**Comment by Noaaan** [comment]
I got 0.9.8 to work on the server, but the other ones seem to not function properly with 1.16.5.
I am working on figuring out what is going on, and will likely push a new snapshot ASAP.

**Comment by Noaaan** [comment]
I think I have figured out the issue. Seems related to Fabric API. It has been fixed in recent commits, but sacrifices global ore spawning everywhere. Will have to fix this later.
