### ISSUE TITLE
Mythic metals keeps crashing

### ISSUE THREAD

**Issue by Cutiestcutcat** [Noaaan/MythicMetals#268]
I'm playing on Java edition 1.21. It keeps crashing from thirty seconds to a few minutes after I open the game. The exit code is 255 and the log it gave me is this: **Caused by: java.lang.IllegalArgumentException: Can't find attribute mythicmetals:fire_vulnerability**

This is the full thing:

**Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Can't find attribute mythicmetals:fire_vulnerability
	at net.minecraft.class_5132.method_26865(class_5132.java:21)
	at net.minecraft.class_5132.method_26862(class_5132.java:27)
	at net.minecraft.class_5131.method_26852(class_5131.java:68)
	at net.minecraft.class_1309.method_45325(class_1309.java:1977)
	at net.minecraft.class_1309.localvar$dce000$mythicmetals$changeFireDamage(class_1309.java:16896)
	at net.minecraft.class_1309.method_5643(class_1309.java)
	at net.minecraft.class_1420.method_5643(class_1420.java:225)
	at net.minecraft.class_1297.method_5730(class_1297.java:605)
	at net.minecraft.class_1297.method_5670(class_1297.java:545)
	at net.minecraft.class_1309.method_5670(class_1309.java:406)
	at net.minecraft.class_1308.method_5670(class_1308.java:302)
	at net.minecraft.class_1297.method_5773(class_1297.java:487)
	at net.minecraft.class_1309.method_5773(class_1309.java:2468)
	at net.minecraft.class_1308.method_5773(class_1308.java:372)
	at net.minecraft.class_1420.method_5773(class_1420.java:131)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	... 5 more**

**Comment by Noaaan** [comment]
This might be a duplicate of https://github.com/Noaaan/MythicMetals/issues/259
If not, the crash reason is likely the same

**Comment by Cutiestcutcat** [comment]
Oh. Sorry I didn't see that. Thank you for the response, I do have eternal starlight installed and it solved the issue.
