### ISSUE TITLE
Fabric MythicMetals v0.12.0 crash on server side

### ISSUE THREAD

**Issue by Panderine** [Noaaan/MythicMetals#67]
```
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback in environment type SERVER

	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.13.3.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.13.3.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.13.3.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]

	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

	at nourl.mythicmetals.abilities.Ability.addTooltip(Ability.java:76) ~[mythicmetals-0.12.0-alpha.jar:?]

	at nourl.mythicmetals.abilities.Ability.addItem(Ability.java:45) ~[mythicmetals-0.12.0-alpha.jar:?]

	at nourl.mythicmetals.abilities.Abilities.init(Abilities.java:32) ~[mythicmetals-0.12.0-alpha.jar:?]

	at nourl.mythicmetals.MythicMetals.onInitialize(MythicMetals.java:45) ~[mythicmetals-0.12.0-alpha.jar:?]

	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]

	... 16 more
```

**Comment by Noaaan** [comment]
Thanks for reporting this!

**Comment by Panderine** [comment]
sorry, is this fix released anywhere or not yet? Thanks!

**Comment by Noaaan** [comment]
The fix is not released yet, as I have been fixing more bugs related to the new banglum ores. 
I think I you can expect 0.12.0 to be released sometime this weekend.

**Comment by Panderine** [comment]
no problem. Thanks!
